from rest_framework import serializers
from basic.models import AVItem

class AVItemSerializer(serializers.ModelSerializer):
    class Meta:
        model=AVItem
        view_name = 'avitem-detail'
        fields = ('pk',
                  'uid',
                  'original_id',
                  'collection_id',
                  'item_title',
                  'series_title',
                  'episode_title',
                  'can_number',
                  'original_can_number',
                  'call_number',
                  'date_created',
                  'Credits',
                  'description',
                  'location',
                  'format_duration',
                  'media_type',
                  'copies',
                  "other_notes",
                  "Base",
                  "Sound_format_type",
                  "digital_preservation",
                  "lto_number",
                  "status",
                  "Copyright",
                  "gauge",
                  "footage",
                  "frame_rate",
                  "color",
                  "adv_color",
                  "aspect_ratio",
                  "anamorphic",
                  "sound",
                  "sound_content_type",
                  "sound_field",
                  "Clean",
                  "resolution",
                  "sample_encoding",
                  "return_on_original_reel",
                  "mold",
                  "shrinkage",
                  "ad_strip",
                  "track_count",
                  "stock",)

class ToyAVSerializer(serializers.ModelSerializer):
    class Meta:
        model = AVItem
        fields = ('pk',
                  "uid",
                    "original_id",
                    "collection_id",
                    "item_title",
                    "series_title",
                    "episode_title",
                    "can_number",
                    "original_can_number",
                    "call_number",
                    "date_created",
                    "Credits",
                    "description",
                    "location",
                    "format_duration",
                    "media_type",
                    "copies",
                    "other_notes",
                    "Base",
                    "Sound_format_type",
                    "digital_preservation",
                    "lto_number",
                    "status",
                    "Copyright",
                    "gauge",
                    "footage",
                    "frame_rate",
                    "color",
                    "adv_color",
                    "aspect_ratio",
                    "anamorphic",
                    "sound",
                    "sound_content_type",
                    "sound_field",
                    "Clean",
                    "resolution",
                    "sample_encoding",
                    "return_on_original_reel",
                    "mold",
                    "shrinkage",
                    "ad_strip",
                    "track_count",
                    "stock",
                    )
