# Generated by Django 2.1 on 2018-12-06 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AVItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('items_title', models.CharField(max_length=100, unique=True)),
            ],
            options={
                'ordering': ('items_title',),
            },
        ),
    ]
