# Generated by Django 2.1 on 2018-12-06 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitem',
            name='call_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='can_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='collection_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='credits',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='date_created',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='description',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='episode_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='item_title',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='location',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='original_can_number',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='original_id',
            field=models.CharField(blank=True, max_length=15),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='series_title',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
