# Generated by Django 2.1 on 2018-12-17 19:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avitem',
            old_name='Credits11',
            new_name='Credits',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='call_number11',
            new_name='call_number',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='can_number11',
            new_name='can_number',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='collection_id11',
            new_name='collection_id',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='date_created11',
            new_name='date_created',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='description11',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='episode_title11',
            new_name='episode_title',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='footage11',
            new_name='footage',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='format_duration11',
            new_name='format_duration',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='item_title11',
            new_name='item_title',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='location11',
            new_name='location',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='lto_number11',
            new_name='lto_number',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='original_can_number11',
            new_name='original_can_number',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='original_id11',
            new_name='original_id',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='other_notes11',
            new_name='other_notes',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='series_title11',
            new_name='series_title',
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='uid11',
            new_name='uid',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='adv_color11',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='aspect_ratio11',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='color11',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='copies11',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='copyright_111',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='digital_preservation11',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='frame_rate11',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='gauge11',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='media_type11',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='status11',
        ),
        migrations.AddField(
            model_name='avitem',
            name='Copyright',
            field=models.CharField(blank=True, choices=[('', ''), ('open', 'Open'), ('restricted', 'Restricted')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='avitem',
            name='adv_color',
            field=models.CharField(blank=True, choices=[('', ''), ('ektachrome', 'Ektachrome'), ('kodachrome', 'Kodachrome'), ('technicolor', 'Technicolor'), ('anscochrome', 'Anscochrome'), ('eco', 'Eco'), ('eastman', 'Eastman')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='avitem',
            name='aspect_ratio',
            field=models.CharField(blank=True, choices=[('', ''), ('1.18:1', '1.18:1'), ('1.33:1', '1.33:1'), ('1.37:1', '1.37:1'), ('1.66:1', '1.66:1'), ('1.85:1', '1.85:1'), ('2.35:1', '2.35:1'), ('2.39:1', '2.39:1'), ('2.59:1', '2.59:1'), ('2.66:1', '2.66:1')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='avitem',
            name='color',
            field=models.CharField(blank=True, choices=[('', ''), ('color', 'COLOR'), ('black and white', 'BLACK AND WHITE')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='avitem',
            name='copies',
            field=models.CharField(blank=True, choices=[('', ''), ('yes', 'Yes'), ('no', 'No')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='avitem',
            name='digital_preservation',
            field=models.CharField(blank=True, choices=[('', ''), ('yes', 'Yes'), ('no', 'No')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='avitem',
            name='frame_rate',
            field=models.CharField(blank=True, choices=[('', ''), ('16 fps', '16 fps'), ('18 fps', '18 fps'), ('24 fps', '24 fps')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='avitem',
            name='gauge',
            field=models.CharField(blank=True, choices=[('', ''), ('8mm', '8mm'), ('super 8mm', 'Super 8mm'), ('16mm', '16mm'), ('35mm', '35mm'), ('35/32mm', '35/32mm')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='avitem',
            name='media_type',
            field=models.CharField(blank=True, choices=[('', ''), ('film', 'Film'), ('video', 'Video'), ('audio', 'Audio')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='avitem',
            name='status',
            field=models.CharField(blank=True, choices=[('', ''), ('on shelf', 'On Shelf'), ('conservation', 'Conservation'), ('vendor', 'Vendor'), ('loan', 'Loan')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='sound',
            field=models.CharField(blank=True, choices=[('', ''), ('sound', 'Sound'), ('silent', 'Silent')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='sound_content_type',
            field=models.CharField(blank=True, choices=[('', ''), ('composite track', 'Composite Track'), ('sound content', 'Sound Content')], default='', max_length=25),
        ),
    ]
