# Generated by Django 2.1 on 2018-12-06 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20181206_1226'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avitem',
            options={},
        ),
    ]
