# Generated by Django 2.1 on 2018-12-06 17:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0002_auto_20181206_1107'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='AVItems',
            new_name='AVItem',
        ),
    ]
