# Generated by Django 2.1 on 2018-12-06 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_auto_20181206_1109'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='avitem',
            options={'ordering': ('item_title',)},
        ),
        migrations.RenameField(
            model_name='avitem',
            old_name='items_title',
            new_name='item_title',
        ),
    ]
