# Generated by Django 2.1 on 2018-12-07 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0003_avitem_formatduration'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avitem',
            old_name='formatduration',
            new_name='format_duration',
        ),
        migrations.AddField(
            model_name='avitem',
            name='media_type',
            field=models.CharField(choices=[('film', 'FILM'), ('video', 'VIDEO'), ('audio', 'AUDIO')], default='film', max_length=6),
        ),
    ]
