# Generated by Django 2.1 on 2018-12-07 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20181207_1517'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitem',
            name='copies',
            field=models.BooleanField(default=False),
        ),
    ]
