# Generated by Django 2.1 on 2018-12-06 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0004_auto_20181206_1112'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitem',
            name='call_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='avitem',
            name='can_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='avitem',
            name='collection_id',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='avitem',
            name='credits',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='avitem',
            name='date_created',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='avitem',
            name='description',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='avitem',
            name='episode_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='avitem',
            name='location',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='avitem',
            name='original_can_number',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='avitem',
            name='original_id',
            field=models.CharField(default='', max_length=15),
        ),
        migrations.AddField(
            model_name='avitem',
            name='series_title',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AddField(
            model_name='avitem',
            name='uid',
            field=models.CharField(default='', max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='item_title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
