# Generated by Django 2.1 on 2018-12-17 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_avitem_sound_format_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitem',
            name='format_duration',
            field=models.TimeField(blank=True, default='00:00:00', null=True),
        ),
    ]
