# Generated by Django 2.1 on 2018-12-06 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0005_auto_20181206_1159'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitem',
            name='uid',
            field=models.CharField(default=None, max_length=15, unique=True),
        ),
    ]
