# Generated by Django 2.1 on 2018-12-07 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0006_auto_20181207_1531'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitem',
            name='adv_color',
            field=models.CharField(choices=[('ektachrome', 'EKTACHROME'), ('kodachrome', 'KODACHROME'), ('technicolor', 'TECHNICOLOR'), ('anscochrome', 'ANSCOCHROME'), ('eco', 'ECO'), ('eastman', 'EASTMAN')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='avitem',
            name='color',
            field=models.CharField(choices=[('color', 'COLOR'), ('black and white', 'BLACK AND WHITE')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='avitem',
            name='copyright',
            field=models.CharField(choices=[('open', 'OPEN'), ('restricted', 'RESTRICTED')], default='', max_length=15),
        ),
        migrations.AddField(
            model_name='avitem',
            name='footage',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='avitem',
            name='frame_rate',
            field=models.CharField(choices=[('16 fps', '16 fps'), ('18 fps', '18 fps'), ('24 fps', '24 fps')], default='16 fps', max_length=15),
        ),
        migrations.AddField(
            model_name='avitem',
            name='gauge',
            field=models.CharField(choices=[('8mm', '8mm'), ('super 8mm', 'Super 8mm'), ('16mm', '16mm'), ('35mm', '35mm'), ('35/32mm', '35/32mm')], default='', max_length=15),
        ),
    ]
