# Generated by Django 2.1 on 2018-12-07 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0008_auto_20181207_1637'),
    ]

    operations = [
        migrations.AlterField(
            model_name='avitem',
            name='ad_strip',
            field=models.CharField(choices=[('', ''), ('0', '0'), ('0.5', '0.5'), ('1', '1'), ('1.5', '1.5'), ('2', '2'), ('2,5', '2,5'), ('3', '3')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='adv_color',
            field=models.CharField(choices=[('', ''), ('ektachrome', 'Ektachrome'), ('kodachrome', 'Kodachrome'), ('technicolor', 'Technicolor'), ('anscochrome', 'Anscochrome'), ('eco', 'Eco'), ('eastman', 'Eastman')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='aspect_ratio',
            field=models.CharField(choices=[('', ''), ('1.18:1', '1.18:1'), ('1.33:1', '1.33:1'), ('1.37:1', '1.37:1'), ('1.66:1', '1.66:1'), ('1.85:1', '1.85:1'), ('2.35:1', '2.35:1'), ('2.39:1', '2.39:1'), ('2.59:1', '2.59:1'), ('2.66:1', '2.66:1')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='color',
            field=models.CharField(choices=[('', ''), ('color', 'COLOR'), ('black and white', 'BLACK AND WHITE')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='copyright',
            field=models.CharField(choices=[('', ''), ('open', 'OPEN'), ('restricted', 'RESTRICTED')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='frame_rate',
            field=models.CharField(choices=[('', ''), ('16 fps', '16 fps'), ('18 fps', '18 fps'), ('24 fps', '24 fps')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='gauge',
            field=models.CharField(choices=[('', ''), ('8mm', '8mm'), ('super 8mm', 'Super 8mm'), ('16mm', '16mm'), ('35mm', '35mm'), ('35/32mm', '35/32mm')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='media_type',
            field=models.CharField(choices=[('', ''), ('film', 'Film'), ('video', 'Video'), ('audio', 'Audio')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='resolution',
            field=models.CharField(choices=[('', ''), ('hd', 'HD'), ('2k', '2k'), ('4k', '4k'), ('5k', '5k')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='sample_encoding',
            field=models.CharField(choices=[('', ''), ('linear 10 bit', 'Linear 10 bit'), ('linear 16 bit', 'Linear 16 bit'), ('logarithmic 10 bit', 'Logarithmic 10 bit')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='sound',
            field=models.CharField(choices=[('', ''), ('sound', 'SOUND'), ('silent', 'SILENT')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='sound_content_type',
            field=models.CharField(choices=[('', ''), ('composite track', 'COMPOSITE TRACK'), ('sound content', 'SOUND CONTENT')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='sound_field',
            field=models.CharField(choices=[('', ''), ('mono', 'MONO'), ('stero', 'STEREO')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='status',
            field=models.CharField(choices=[('', ''), ('on shelf', 'On Shelf'), ('conservation', 'Conservation'), ('vendor', 'Vendor'), ('loan', 'Loan')], default='', max_length=15),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='stock',
            field=models.CharField(choices=[('', ''), ('Kodak', 'Kodak'), ('Ferrania', 'Ferrania'), ('3M', '3M'), ('Agfa-Gevaert', 'Agfa-Gevaert'), ('Pathe', 'Pathe'), ('unknown', 'unknown')], default='', max_length=25),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='track_count',
            field=models.CharField(choices=[('', ''), ('0', '0'), ('1', '1'), ('2', '2')], default='', max_length=7),
        ),
    ]
