# Generated by Django 2.1 on 2018-12-07 23:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0009_auto_20181207_1702'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avitem',
            old_name='copyright',
            new_name='copyright_1',
        ),
    ]
