# Generated by Django 2.1 on 2018-12-07 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0010_auto_20181207_1712'),
    ]

    operations = [
        migrations.RenameField(
            model_name='avitem',
            old_name='credits',
            new_name='credits_1',
        ),
    ]
