# Generated by Django 2.1 on 2018-12-07 23:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0011_auto_20181207_1717'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='avitem',
            name='anamorphic',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='clean',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='copies',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='digital_preservation',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='mold',
        ),
        migrations.RemoveField(
            model_name='avitem',
            name='return_on_original_reel',
        ),
    ]
