# Generated by Django 2.1 on 2018-12-07 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('basic', '0012_auto_20181207_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='avitem',
            name='anamorphic',
            field=models.CharField(choices=[('', ''), ('yes', 'Yes'), ('no', 'No')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='avitem',
            name='clean',
            field=models.CharField(choices=[('', ''), ('yes', 'Yes'), ('no', 'No')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='avitem',
            name='copies',
            field=models.CharField(choices=[('', ''), ('yes', 'Yes'), ('no', 'No')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='avitem',
            name='digital_preservation',
            field=models.CharField(choices=[('', ''), ('yes', 'Yes'), ('no', 'No')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='avitem',
            name='mold',
            field=models.CharField(choices=[('', ''), ('treated', 'Treated'), ('no', 'No')], default='', max_length=7),
        ),
        migrations.AddField(
            model_name='avitem',
            name='return_on_original_reel',
            field=models.CharField(choices=[('', ''), ('yes', 'Yes'), ('no', 'No')], default='', max_length=7),
        ),
        migrations.AlterField(
            model_name='avitem',
            name='shrinkage',
            field=models.FloatField(default='0.0'),
        ),
    ]
